### ISSUE TITLE
GCP - Automate User Management in Terraform

### ISSUE THREAD

**Issue by kaxil** [astronomer/terraform#12]
Users and IAM should be automated in terraform.

For example, having Terraform variables with a list of users email accounts who would be assigned roles

**Comment by kaxil** [comment]
Have implemented 2 variables as a part of https://github.com/astronomer/terraform/commit/251502f8ab48e81664c89acffc847eb8ee899d4a

**Comment by sjmiller609** [comment]
Kaxil did complete this one
