### ISSUE TITLE
Set up CI/CD on drone

### ISSUE THREAD

**Issue by schnie** [astronomer/terraform#15]
We should set this repo set up on drone so we can automate linting, testing (and maybe deployment?) of our changes. We'll also need to create a GCP project to deploy into. A similar setup will need to be created on AWS as well.

**Comment by schnie** [comment]
Came across this: https://keel.sh/v1/examples/enabling-auto-updates.html, a Kubernetes Operator to automate deployments from image pushes. 

Just posting here to get more eyes on it. Not sure if we want this or not.

**Comment by ianstanton** [comment]
- [ ] Add `.drone.yml` to repo

- [ ] Add `tfvars` as drone secrets
