### ISSUE TITLE
GCP - Add optional GCS bucket to back the registry

### ISSUE THREAD

**Issue by schnie** [astronomer/terraform#17]
We currently back the registry with a `StatefulSet` and a PV in Kubernetes. This will now be optionally backed by external storage. Our cloud version should use a GCS bucket for infinite scalability.

This is closely related to https://github.com/astronomer/helm.astronomer.io/issues/125

**Comment by kaxil** [comment]
Resolved by https://github.com/astronomer/terraform/pull/24
