### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by ryw** [astronomer/terraform#25]

**Comment by sjmiller609** [comment]
https://github.com/astronomer/terraform-kubernetes-astronomer-system-components/issues/1
https://github.com/astronomer/terraform-google-astronomer-gcp/issues/2
https://github.com/astronomer/terraform-kubernetes-astronomer/issues/2
https://github.com/astronomer/terraform-aws-astronomer-aws/issues/5
https://github.com/astronomer/terraform_wrapper_scripts/issues/2
