### ISSUE TITLE
GCP - Cloud SQL for PostgreSQL

### ISSUE THREAD

**Issue by ianstanton** [astronomer/terraform#3]
Configure Terraform resource for Google Cloud SQL PostgreSQL database.
**Requirements:**
* Highly available
* Private IP
* On same private network as cluster
* Query through bastion(?)

**Comment by kaxil** [comment]
Fixed by https://github.com/astronomer/terraform/commit/a2b3b2158e34828742aa07efe55e94c3341ac186
