### ISSUE TITLE
GCP - Add Second Node Pool for gVisor

### ISSUE THREAD

**Issue by schnie** [astronomer/terraform#31]
To support Istio and gVisor, we'll need to separate the system into two node pools. The platform can be installed into the first node pool and utilize istio. The second node pool should be used for airflow deployments and have  gVisor enabled.

**Comment by schnie** [comment]
@sjmiller609 assuming this is just the terraform component, we can close this out right?

**Comment by sjmiller609** [comment]
https://github.com/astronomer/terraform-google-astronomer-gcp/blob/1f825ea9690f20429aba599485ab2df9ba25b3b9/node_pools.tf
