### ISSUE TITLE
Allow tag injection via terraform

### ISSUE THREAD

**Issue by arigesher** [astronomer/terraform#33]
It would be lovely we could specify an array of tags in the terraform variables file when bringing up a new installation.  Those tags would be applied to all the various pieces of infrastructure that terraform creates.

This would enable easy cost accounting on how much each cluster is costing.

**Comment by skuldy** [comment]
This would be support for arguments tags and volume_tags for aws_instance in terraform: https://www.terraform.io/docs/providers/aws/r/instance.html.

**Comment by sjmiller609** [comment]
Ok, I’ll track this issue in the applicable repo. This repo is getting phased out in favor of publishing terraform modules https://github.com/astronomer/terraform-aws-astronomer-aws/issues/4
